### PR TITLE
Fix dates to force correct format

### PR DESCRIPTION
**Pull request by tmeasday**
The dates were being formatted in a way that google wasn't happy with. This commit uses the specced format.

### CODE REVIEW

**Comment by lassebunk** [comment]
Thanks! Could we have the time also, e.g. '2004-12-23T18:00:15+00:00' like in http://www.sitemaps.org/protocol.html ? Thanks in advance :)

**Comment by tmeasday** [comment]
Done.

**Comment by lassebunk** [comment]
Thanks :)

**Comment by tmeasday** [comment]
Hey Lasse,

Thanks for merging all my pull requests! Is there any chance you could do another release with these changes? I'd love to no t have to use my fork any more. 

Cheers,
Tom

**Comment by lassebunk** [comment]
Hey Tom,

Thanks for all your pull requests, they really are a great help.
I just discovered that the `%:z` part in `strftime("%Y-%m-%dT%H:%M:%S%:z")` doesn't work. It just returns :z. WIthout the colon it works fine but without colon between the hour and minutes.

What to do?

/Lasse

**Comment by tmeasday** [comment]
Ahh, I think this is a ruby 1.8 thing (I'm on 1.9).

You could try adding .to_datetime before calling .strftime, ie.

```
page.last_mod.to_datetime.strftime("%Y-%m-%dT%H:%M:%S%:z")
```

And see how that goes? (seems to work for me on a 1.8 console at least).

Cheers,
Tom

**Comment by lassebunk** [comment]
Yeah that works :-) Will you fix it?

/Lasse

2012/1/6 Tom Coleman <
reply@reply.github.com

**Pull request merged**
