### PR TITLE
Disabling the layout 

### PR DESCRIPTION
**Pull request by vinu**
Rather than layout nil, layout false is the correct way in rails.3.2 - Please update :)

### CODE REVIEW

**Comment by lassebunk** [comment]
Hi Vinu,

We have already implemented this in another commit – but thanks anyway! :-)

Best regards,
/Lasse

**Comment by vinu** [comment]
oh thanks :) - But I didn't see it in the master branch 

regards
Vinu

**Comment by lassebunk** [comment]
Hi again, Vinu :-)

You can see it here:
https://github.com/lassebunk/dynamic_sitemaps/blob/master/app/controllers/sitemaps_controller.rb

Regards,
/Lasse

**Comment by vinu** [comment]
yeah there it is layout nil - But we need to have layout false - to disable the layout - else the layout gets applied

regards
Vinu

**Comment by lassebunk** [comment]
Hi again, Vinu :)

Okay, I hope you can find out :)

Best regards,
/Lasse

2012/6/14 Vinu Varghese <
reply@reply.github.com

**Comment by vinu** [comment]
Hey :) 
Yes I saw it, But I feel this https://github.com/vinu/dynamic_sitemaps/blob/master/app/controllers/sitemaps_controller.rb#L2 is the correct way to disable the layout 
(Only this way worked for me )
What's your thoughts?

regards
Vinu

**Comment by vinu** [comment]
I think layout false is the correct method
please see http://apidock.com/rails/AbstractController/Layouts/ClassMethods/layout
layout false - There is no layout
layout nil - Force default layout behavior with inheritance

regards
Vinu

**Comment by lassebunk** [comment]
Hi again, Vinu :-)

Sorry! – I misunderstood what you meant :)
I have merged the pull request, updated the gem to the version you specified, and added you to the list of contributors to the gem.

Thanks so much! :-)

Best regards,
/Lasse

**Comment by vinu** [comment]
Hi Lasse :)
Thanks pal :)

I loved your code to generate site map dynamically - nice :)

regards
Vinu

**Comment by lassebunk** [comment]
Hi Vinu :-)

No prob! :-)
I like it so much when people can use my plugins :-)
Do you also know/use my Gretel gem for making breadcrumbs?

Thanks again so much for contributing – it really helps! :-)

/Lasse

2012/6/15 Vinu Varghese <
reply@reply.github.com

**Pull request merged**
